### ISSUE TITLE
BUG: Dates

### ISSUE THREAD

**Issue by larsoner** [mne-tools/fiff-constants#24]
Dates are currently stored in `meas_date` in 32-bit (signed) integers. However, this is going to be problematic in 2038, since that is the latest date that can be stored using int32 seconds (see [this issue](https://github.com/mne-tools/mne-python/pull/7016#issuecomment-550131763)). And in the linked issue, it seems like it could be problematic sooner/today, because of how BIDS standardization and anonymization works.

It would be good if we could store dates in 64-bit integers, which [seems to be the C convention anyway](https://en.wikipedia.org/wiki/Integer_(computer_science)#Common_integral_data_types). It looks like this is already a [supported primitive](https://github.com/mne-tools/fiff-constants/blob/master/DictionaryTypes.txt#L118).

@jnenonen what do you think about:

1. Adding a `meas_date_long` tag
2. In reading `info` structures, prefer to save and load the `meas_date_long` tag, but fall back to `meas_date` / `int32` when the `long` one is not available?

I think this would be a few lines for us over in MNE, but wanted to see if this would be feasible for MEGIN, and if this seems like a reasonable approach to having larger dates.

cc @mshamalainen @agramfort in case you have thoughts/ideas as well

**Comment by jnenonen** [comment]
Hi Eric,

This is a known issue, but there may not be a quick workaround like adding new tag like meas_date_long. It would work in properly coded applications, but also break many other applications such as our own legacy software.

The best way would be to fix all 32-bit related problems in a major overhaul of the fiff-version. We have to do it sooner rather than later,  but plan it very carefully because it will have major implications in all software handling FIFF-format files.

Unfortunately I cannot give any estimate when we could start such format overhauling, but let’s continue this discussion…

BR, Jukka

[NENONEN_Outlook Signature]

**Comment by larsoner** [comment]
Okay I'll close this issue/idea then in favor of overhauling the 32-bit-ness more globally eventually.

**Comment by mkajola** [comment]
Hello,

The current dictionary (at least the copy I have here), has a bug in date types. It has probably been there from the start.
They are marked as int32 while they are int32*(2).
I don’t think there should be tag meas_date_long, since the tags are specifying meanings, not encodings.
If the long dates are needed, I would rather specify alternative encoding to the tag. Simplest would be int64*(2).
Unfortunately not all programs check what is the type of the data. This means that the change will break silently many things.

I would not change this at this point unless there is no real need for this. There is still some time to 2032.
That C defines date as 64 bits is not a reason, since file encodings and software internal representations are different domains, and there is no fundamental reason why the encodings in both should be same. Assuming so is not good software design.

t. mjk
